# configs/config.yaml

# Wandb_Project information
project_name: "segmentation_project2"
wandb_name: "deeplabv3_resnet101"

# Data paths
data:
  image_root_train: "data/train/DCM"
  label_root_train: "data/train/outputs_json"
  image_root_test: "data/test/DCM"
  classes: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
  ]

# Training parameters
training:
  epochs: 20
  batch_size: 16
  num_workers: 32
  learning_rate: 0.0001
  val_every: 1
  random_seed: 42
  

# Model parameters
model:
  name: "deeplabv3_resnet101"
  pretrained: true

# Output paths
output:
  checkpoint_dir: "../checkpoints"
  name: "deeplabv3_resnet101_model.pt"
  output_csv: "../output/submission2.csv"

# test parameters
test:
  batch_size: 16
  num_workers: 32
  resize_height: 512
  resize_width: 512
  original_height: 2048
  original_width: 2048
  threshold: 0.5
