program: train.py
name: segmentation_sweep
method: grid # 만약 모든 조합을 보고 싶으면 grid/ 베이즈추론하고 싶으면 bayes
command:
  - /home/jaegun/miniconda3/envs/AI_tech/bin/python  # Python 실행 경로(which python 을 통해 본인의 파이썬 실행경로적으셈)
  - ${program}  # train.py 실행할 프로그램 이름입니다. 위에서 program: train.py로 지정되어 있으므로, 실제로는 train.py가 여기에 대입됩
  - --config=configs/config.yaml  # config 파일 경로

metric:
  name: Average Dice Score
  goal: maximize

parameters:
  train_lr:  # train 관련 하이퍼파라미터 (lr)
    values: [0.001, 0.0001]  # 두 가지 값으로 제한
    
  train_batch_size:  # train 관련 하이퍼파라미터 (batch size)
    values: [4]

  max_epoch:  # train 관련 하이퍼파라미터 (epoch)
    values: [70]  # 

  model_name:  # model 이름
    values: ["Unet"] #, "DeepLabV3", "UnetPlusPlus"

  model_encoder_name:  # model encoder
    values: ["efficientnet-b7",  "efficientnet-b0"]

  model_encoder_weight:
    values: ["advprop"] #imagenet,advprop 2개있음

  loss_name:  # loss 관련 하이퍼파라미터
    values: ["CombinedLoss"] # BCEWithLogitsLoss,DiceLoss 

  scheduler_name:  # scheduler 관련 하이퍼파라미터
    values: ["CosineAnnealingLR"] # "MultiStepLR", "ReduceLROnPlateau"

