# configs/mmseg_config.yaml

# model config
model_config: './mmsegmentation/my_configs/hrnet2.py'
# image resize
image_size: &image_size 1024 #&는 앵커로, 특정값은 별칭(*)으로 저장하여 yaml 에서 해당값을 여러번 재사용할 수 있게함.

# 최대 epochs
max_epoch: &max_epoch 20
# random seed값
seed: 42

by_epoch: False
amp: True
resume: False
# train 매개변수 설정
train:
  max_epoch: *max_epoch
  image_root: "data/train/DCM"
  label_root: "data/train/outputs_json"
  train_batch_size: 4
  num_workers : 4
  lr: 1e-4
  weight_decay: 1e-6



# validation 관련 인자
validation:
  val_fold: 0
  val_interval: 1
  num_workers: 2
  threshold: 0.5
  val_batch_size: 2

# # 스케줄러 관련 설정
# scheduler:
#   name: CosineAnnealingLR  # 스케줄러 이름
#   parameters:             # 스케줄러 파라미터
#     T_max: *max_epoch
#     eta_min: 1e-6

# # loss 관련설정
# loss:
#   name: CombinedLoss
#   parameters: {} # dict 형태로 작성해야함
    





# #test 관련 
# test:
#   image_root: "data/test/DCM"
#   model_path: "checkpoints"
#   model_path2: *model_name #model_path/model_path2/model_name 으로 model 가져옴.
#   model_file: "best_198epoch_0.9518.pt"
#   output_csv: "output/submission3.csv"

# Output paths
output:
  checkpoint_dir: "../checkpoints"
  # name: "deeplabv3_resnet101_model.pt"




# checkpoint 저장 경로
save_dir: 'mmseg_results'  # 기본 저장 경로

