# configs/mmseg_config.yaml

#
model_config: &model_name swin_l_BCEDICE.py
# image resize
image_size: &image_size 1024 #&는 앵커로, 특정값은 별칭(*)으로 저장하여 yaml 에서 해당값을 여러번 재사용할 수 있게함.

# 최대 epochs
max_epoch: &max_epoch 20

# random seed값
seed: 42

by_epoch:  False
# wandb
wandb:
  api_key: ##본인의 api 키 적으시면 됩니다.
  team_name: CV_SOTA
  project_name: "Segmentation_project"
  entity_name: "jupark0920-tukorea-org"
  exp_name: *model_name

# train 매개변수 설정
train:
  max_epoch: *max_epoch
  batch_size: 2
  num_workers : 8
  lr: 5e-5
  weight_decay: 1e-4

# validation 관련 인자
validation:
  val_fold: 0
  val_interval: 1
  num_workers: 2
  threshold: 0.5
  batch_size: 2

test:
  num_workers: 2
  threshold: 0.5
  batch_size: 2
# 스케줄러 관련 설정
scheduler:
  name: CosineAnnealingLR  # 스케줄러 이름
  parameters:             # 스케줄러 파라미터
    T_max: *max_epoch
    eta_min: 1e-6

amp: True # AMP 사용시 True

# checkpoint 저장 경로
save_dir: mmseg_results  # 기본 저장 경로

# 먼가 save_dir랑 의미가 다른느낌
checkpoint: iter_320.pth

