# configs/mmseg_config.yaml

#
model_config: mmsegmentation/my_configs/hrnetv2.py
# image resize
image_size: &image_size 1024 #&는 앵커로, 특정값은 별칭(*)으로 저장하여 yaml 에서 해당값을 여러번 재사용할 수 있게함.

# 최대 epochs
max_epoch: &max_epoch 20

# random seed값
seed: 42

by_epoch:  False




# train 매개변수 설정
train:
  max_epoch: *max_epoch
  train_batch_size: 4
  num_workers : 8
  lr: 1e-4
  weight_decay: 1e-6

# validation 관련 인자
validation:
  val_fold: 0
  val_interval: 1
  num_workers: 2
  threshold: 0.5
  val_batch_size: 2


# 스케줄러 관련 설정
scheduler:
  name: CosineAnnealingLR  # 스케줄러 이름
  parameters:             # 스케줄러 파라미터
    T_max: *max_epoch
    eta_min: 1e-6

amp: True # AMP 사용시 True

#test 관련 
test:
  output_csv: "output/submission3.csv"


# checkpoint 저장 경로
save_dir: mmseg_results  # 기본 저장 경로

# 학습이 끝나고 나오는 pt 저장경로를 복사붙여넣기 하면 됩니다.
pt_dir: mmseg_results/last_checkpoint

# # wandb
# wandb:
#   api_key: ##본인의 api 키 적으시면 됩니다.
#   team_name: CV_SOTA
#   project_name: "Segmentation_project"
#   exp_name: *model_name
#   use_sweep: False # True 라고 적어야 사용합니다.
#   sweep_path: "configs/config_sweep.yaml" 